apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod
          imagePullPolicy: Never
          env: 
            - name: FLASK_APP 
              value: 'todo_app/app'
            - name: FLASK_RUN_HOST
              value: '0.0.0.0' 
            - name: FLASK_ENV
              value: 'docker' 
            - name: FLASK_DEBUG
              value: 'false' 
            - name: PYTHONUNBUFFERED
              value: '1' 
            - name: LOG_LEVEL
              value: 'DEBUG' 
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 80