services:
  test-ci:
    build:
      dockerfile: Dockerfile
      context: .
      target: test-ci
    image: todo-app:tests
    command: --ignore todo_app/tests_e2e
    env_file:
      - .env.test
    volumes:
      - ./todo_app:/app/todo-app/todo_app
  e2e-ci:
    build:
      dockerfile: Dockerfile
      context: .
      target: test-ci
    image: todo-app:tests-e2e
    command: --ignore todo_app/tests
    volumes:
      - ./todo_app:/app/todo-app/todo_app
    environment:
      - MONGO_CONNECTION_STRING
      - MONGO_DATABASE_NAME
  mongo-db:
    image: mongo:7.0
    container_name: mongo_container
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD