services:
  test-ci:
    build:
      dockerfile: Dockerfile
      context: .
      target: test-ci
    image: todo-app:tests
    command: --ignore todo_app/tests_e2e
    env_file:
      - .env.test
    volumes:
      - ./todo_app:/app/todo-app/todo_app
  e2e-ci:
    build:
      dockerfile: Dockerfile
      context: .
      target: test-ci
    image: todo-app:tests-e2e
    command: --ignore todo_app/tests
    volumes:
      - ./todo_app:/app/todo-app/todo_app