services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    image: todo-app:dev
    ports: 
     - 3001:5000
    env_file:
      - .env
    volumes:
      - ./todo_app:/app/todo-app/todo_app
  test:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    image: todo-app:tests
    command: --ignore todo_app/tests_e2e
    env_file:
      - .env.test
    volumes:
      - ./todo_app:/app/todo-app/todo_app
  e2e:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    image: todo-app:tests-e2e
    command: --ignore todo_app/tests
    env_file:
      - .env
    volumes:
      - ./todo_app:/app/todo-app/todo_app